[build]
  publish = "client/build"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
